import { NextAppDirEmotionCacheProvider } from 'tss-react/next/appDir';

import {
  AuthProvider,
  MuiProvider,
  ReduxProvider,
} from '@app/components/global';
import { inter } from '@app/utils/fonts';

import type { Metadata } from 'next';

import '@app/styles/index.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={inter.className}>
      <head></head>
      <body id="__next">
        {/* Temporary SSR fix */}
        <NextAppDirEmotionCacheProvider options={{ key: 'css' }}>
          <AuthProvider>
            <MuiProvider>
              <ReduxProvider>{children}</ReduxProvider>
            </MuiProvider>
          </AuthProvider>
        </NextAppDirEmotionCacheProvider>
      </body>
    </html>
  );
};

export default RootLayout;
